### ISSUE TITLE
Error loading productive data

### ISSUE THREAD

**Issue by fnwirth** [medizininformatik-initiative/Projectathon7-VHF-DataSHIELD#3]
When using the current version of [ds-data-import.R](https://github.com/medizininformatik-initiative/Projectathon7-VHF-DataSHIELD/blob/main/opal-import/ds-data-import.R) to load productive/real-word data I receive the following error message

```
Error: The data file "Cohort.csv " doesn't have 15 columns. This file doesn't have the structure we expected.
 Please make sure this file has the appropriate structure first and then try again.
Execution halted
```

With the second last version of ds-data-import.R and ds-data-import-functions.R it worked. Is this an issue with the script or is it necessary to re-run the data loading process in the DIZ?

**Comment by tkirsten** [comment]
The data structure has been changed.
The birthday is replaced by person's age. Physically, the column has been dropped while the age column is append to the table (last column). Therefore, all column indexes used by the script need to be updated.

**Comment by fnwirth** [comment]
using new version of script fixes problem
